/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddedCartModal: typeof import('./src/components/modal/AddedCartModal.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ContentSection: typeof import('./src/components/ContentSection.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeaderSection: typeof import('./src/components/HeaderSection.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LiveCountdown: typeof import('./src/components/LiveCountdown.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    ProductDetailModal: typeof import('./src/components/modal/ProductDetailModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
