/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddedCartModal: typeof import('./src/components/modal/AddedCartModal.vue')['default']
    Button: typeof import('primevue/button')['default']
    ContentSection: typeof import('./src/components/ContentSection.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeaderSection: typeof import('./src/components/HeaderSection.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LiveCountdown: typeof import('./src/components/LiveCountdown.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    ProductDetailModal: typeof import('./src/components/modal/ProductDetailModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
  }
}
