/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddedCartModal: typeof import('./src/components/modal/AddedCartModal.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    ContentSection: typeof import('./src/components/ContentSection.vue')['default']
    CustomInputText: typeof import('./src/components/form/CustomInputText.vue')['default']
    CustomRadioButton: typeof import('./src/components/form/CustomRadioButton.vue')['default']
    CustomSelect: typeof import('./src/components/form/CustomSelect.vue')['default']
    CustomTextarea: typeof import('./src/components/form/CustomTextarea.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeaderSection: typeof import('./src/components/HeaderSection.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LiveCountdown: typeof import('./src/components/LiveCountdown.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    ModalError: typeof import('./src/components/modal/ModalError.vue')['default']
    ModalSuccess: typeof import('./src/components/modal/ModalSuccess.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    ProductDetailModal: typeof import('./src/components/modal/ProductDetailModal.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
